from os import environ

CELERY_BROKER_URL = environ["CELERY_BROKER_URL"]
CELERY_RESULT_BACKEND = environ["CELERY_RESULT_BACKEND"]
MONGO_URI = environ['MONGO_URI']
MONGO_DATABASE = environ['MONGO_DATABASE']
MONGO_COLLECTION = environ['MONGO_COLLECTION']
